version: 2.0
jobs:
  build:
    docker:
      - image: tiangolo/uvicorn-gunicorn-fastapi:python3.6
        enviroment:
          MONGO_URI='mongodb://root@localhost'
          MONGO_DATABASE_NAME='markpad_tests'
      - image: circleci/mongo:4.0.9
    working_directory: ~/markpad
    steps:
      - checkout
      - run: pip install --upgrade pip
      - run: pip install --no-cache-dir -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: run tests
          command: |
            mkdir test-reports
            pytest --junitxml=test-reports/junit.xml

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports 