version: 2.0
jobs:
  build:
    docker:
      - image: tiangolo/uvicorn-gunicorn-fastapi:python3.6
        environment:
          MONGO_URI: mongodb://localhost:27017
          MONGO_DATABASE_NAME: markpad_tests
      - image: circleci/mongo:4.0.9
    working_directory: ~/markpad
    steps:
      - checkout
      - run: pip install --upgrade pip
      - run: pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: run tests
          command: |
            mkdir test-reports
            pytest --junitxml=test-reports/junit.xml --cov=./

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports

      - run:
        name: run codecov
        command: /
          codecov